import dotenv from "dotenv";
dotenv.config({ path: ".env.local", override: true });
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";
import bcrypt from "bcryptjs";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

// Brand-specific Unsplash IDs — ✓ = confirmed loaded in browser as LCP
const IMG = {
  // iPhone photos — confirmed working dark/surface iPhone shots
  iphone: [
    "1511707171634-5f897ff02aa9", // ✓ dark iPhone hero
    "1574944985070-8f3ebc6b79d2", // ✓ iPhone on surface
    "1531297484001-80022131f5a1", // not 404'd — desk setup
    "1512941937669-90a1b58e7e9c", // not 404'd — smartphone flat
    "1526406915894-7bcd65f60845", // not 404'd — phone in pocket
    "1511707171634-5f897ff02aa9", // cycle back
    "1574944985070-8f3ebc6b79d2",
    "1531297484001-80022131f5a1",
    "1512941937669-90a1b58e7e9c",
    "1526406915894-7bcd65f60845",
  ],
  // Samsung photos — confirmed Samsung Galaxy shot + not-404'd fillers
  samsung: [
    "1610945415295-d9bbf067e59c", // ✓ Samsung Galaxy
    "1598327105666-5b89351aff97", // not 404'd — phone in use
    "1580910051074-3eb694886505", // not 404'd — phone in hand
    "1531297484001-80022131f5a1", // not 404'd
    "1512941937669-90a1b58e7e9c", // not 404'd
    "1610945415295-d9bbf067e59c", // cycle
    "1598327105666-5b89351aff97",
    "1580910051074-3eb694886505",
  ],
  // Pixel photos — premium phone shots (similar hardware aesthetic)
  pixel: [
    "1580910051074-3eb694886505", // not 404'd — phone in hand
    "1574944985070-8f3ebc6b79d2", // ✓ phone on surface
    "1512941937669-90a1b58e7e9c", // not 404'd
    "1526406915894-7bcd65f60845", // not 404'd
    "1598327105666-5b89351aff97", // not 404'd
    "1511707171634-5f897ff02aa9", // ✓ dark phone
  ],
};

function img(ids: string[], count = 2): string[] {
  return ids.slice(0, count).map(
    (id) => `https://images.unsplash.com/photo-${id}?w=800&q=85&auto=format&fit=crop`
  );
}


function slug(str: string): string {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

async function main() {
  console.log("🌱 Seeding Volta Mobile database...");

  // Create brands
  const apple = await prisma.brand.upsert({
    where: { slug: "apple" },
    create: { name: "Apple", slug: "apple" },
    update: {},
  });

  const samsung = await prisma.brand.upsert({
    where: { slug: "samsung" },
    create: { name: "Samsung", slug: "samsung" },
    update: {},
  });

  const google = await prisma.brand.upsert({
    where: { slug: "google" },
    create: { name: "Google", slug: "google" },
    update: {},
  });

  // Create admin user
  const hashedPassword = await bcrypt.hash("volta@admin2024", 12);
  await prisma.user.upsert({
    where: { email: "admin@voltamobile.co.ke" },
    create: {
      email: "admin@voltamobile.co.ke",
      password: hashedPassword,
      name: "Volta Admin",
    },
    update: {},
  });

  console.log("✅ Brands & admin user created");

  // ---- IPHONES (25) ----
  const iphones = [
    {
      name: "iPhone 15 Pro Max 256GB Natural Titanium",
      modelName: "iPhone 15 Pro Max",
      storageCapacity: "256GB",
      ram: "8GB",
      color: "Natural Titanium",
      condition: "EX_UK" as const,
      batteryHealth: 95,
      priceKES: 89999,
      priceUSD: 692,
      marketPriceKES: 115000,
      marketPriceUSD: 885,
      isFeatured: true,
      images: img(IMG.iphone, 3),
      description: "Pristine condition. Titanium frame with ceramic shield front. A17 Pro chip. All buttons functional. No scratches.",
    },
    {
      name: "iPhone 15 Pro Max 512GB Blue Titanium",
      modelName: "iPhone 15 Pro Max",
      storageCapacity: "512GB",
      ram: "8GB",
      color: "Blue Titanium",
      condition: "EX_UK" as const,
      batteryHealth: 100,
      priceKES: 109999,
      priceUSD: 846,
      marketPriceKES: 140000,
      marketPriceUSD: 1077,
      isFeatured: true,
      images: img(IMG.iphone.slice(1), 3),
      description: "100% battery — like new. USB-C. Action button. Comes with original box.",
    },
    {
      name: "iPhone 15 Pro 128GB Black Titanium",
      modelName: "iPhone 15 Pro",
      storageCapacity: "128GB",
      ram: "8GB",
      color: "Black Titanium",
      condition: "EX_UK" as const,
      batteryHealth: 91,
      priceKES: 79999,
      priceUSD: 615,
      marketPriceKES: 102000,
      marketPriceUSD: 785,
      isFeatured: false,
      images: img(IMG.iphone.slice(2), 2),
      description: "Slim titanium design. A17 Pro chip. 48MP main camera. Minor wear on frame only.",
    },
    {
      name: "iPhone 15 256GB Black",
      modelName: "iPhone 15",
      storageCapacity: "256GB",
      ram: "6GB",
      color: "Black",
      condition: "EX_UK" as const,
      batteryHealth: 93,
      priceKES: 65999,
      priceUSD: 508,
      marketPriceKES: 82000,
      marketPriceUSD: 631,
      isFeatured: true,
      images: img(IMG.iphone.slice(3), 2),
      description: "USB-C, Dynamic Island, A16 Bionic. Excellent condition.",
    },
    {
      name: "iPhone 15 Plus 128GB Yellow",
      modelName: "iPhone 15 Plus",
      storageCapacity: "128GB",
      ram: "6GB",
      color: "Yellow",
      condition: "EX_UK" as const,
      batteryHealth: 88,
      priceKES: 62999,
      priceUSD: 485,
      marketPriceKES: 78000,
      marketPriceUSD: 600,
      isFeatured: false,
      images: img(IMG.iphone.slice(4), 2),
      description: "Large 6.7 inch screen. Dynamic Island. USB-C. Bright yellow color, good condition.",
    },
    {
      name: "iPhone 14 Pro Max 256GB Deep Purple",
      modelName: "iPhone 14 Pro Max",
      storageCapacity: "256GB",
      ram: "6GB",
      color: "Deep Purple",
      condition: "EX_UK" as const,
      batteryHealth: 86,
      priceKES: 74999,
      priceUSD: 577,
      marketPriceKES: 95000,
      marketPriceUSD: 731,
      isFeatured: false,
      images: img(IMG.iphone.slice(5), 2),
      description: "Always-On Display, Dynamic Island, 48MP ProRAW camera. Minor hairline on bottom edge.",
    },
    {
      name: "iPhone 14 Pro Max 512GB Space Black",
      modelName: "iPhone 14 Pro Max",
      storageCapacity: "512GB",
      ram: "6GB",
      color: "Space Black",
      condition: "EX_UK" as const,
      batteryHealth: 89,
      priceKES: 88999,
      priceUSD: 685,
      marketPriceKES: 112000,
      marketPriceUSD: 862,
      isFeatured: false,
      images: img(IMG.iphone.slice(6), 2),
      description: "Max storage, pristine glass, clean battery. Comes with fast charger cable.",
    },
    {
      name: "iPhone 14 Pro 128GB Deep Purple",
      modelName: "iPhone 14 Pro",
      storageCapacity: "128GB",
      ram: "6GB",
      color: "Deep Purple",
      condition: "EX_UK" as const,
      batteryHealth: 84,
      priceKES: 62999,
      priceUSD: 485,
      marketPriceKES: 80000,
      marketPriceUSD: 615,
      isFeatured: false,
      images: img(IMG.iphone.slice(7), 2),
      description: "Pro camera system, Dynamic Island, A16 Bionic. Light scratches on back glass.",
    },
    {
      name: "iPhone 14 256GB Blue",
      modelName: "iPhone 14",
      storageCapacity: "256GB",
      ram: "6GB",
      color: "Blue",
      condition: "EX_UK" as const,
      batteryHealth: 82,
      priceKES: 54999,
      priceUSD: 423,
      marketPriceKES: 70000,
      marketPriceUSD: 538,
      isFeatured: false,
      images: img(IMG.iphone.slice(8), 2),
      description: "Crash Detection, Emergency SOS. Good condition overall.",
    },
    {
      name: "iPhone 14 Plus 128GB Midnight",
      modelName: "iPhone 14 Plus",
      storageCapacity: "128GB",
      ram: "6GB",
      color: "Midnight",
      condition: "EX_UK" as const,
      batteryHealth: 85,
      priceKES: 51999,
      priceUSD: 400,
      marketPriceKES: 67000,
      marketPriceUSD: 515,
      isFeatured: false,
      images: img(IMG.iphone.slice(9), 2),
      description: "Big 6.7 screen, long battery life. Excellent condition.",
    },
    {
      name: "iPhone 13 Pro Max 256GB Sierra Blue",
      modelName: "iPhone 13 Pro Max",
      storageCapacity: "256GB",
      ram: "6GB",
      color: "Sierra Blue",
      condition: "EX_UK" as const,
      batteryHealth: 79,
      priceKES: 58999,
      priceUSD: 454,
      marketPriceKES: 72000,
      marketPriceUSD: 554,
      isFeatured: false,
      images: img(IMG.iphone, 2),
      description: "ProMotion display, macro photography. Battery below 80% threshold.",
    },
    {
      name: "iPhone 13 Pro 256GB Alpine Green",
      modelName: "iPhone 13 Pro",
      storageCapacity: "256GB",
      ram: "6GB",
      color: "Alpine Green",
      condition: "EX_UK" as const,
      batteryHealth: 81,
      priceKES: 51999,
      priceUSD: 400,
      marketPriceKES: 64000,
      marketPriceUSD: 492,
      isFeatured: false,
      images: img(IMG.iphone.slice(1), 2),
      description: "120Hz ProMotion, A15 Bionic. Good overall condition.",
    },
    {
      name: "iPhone 13 256GB Pink",
      modelName: "iPhone 13",
      storageCapacity: "256GB",
      ram: "4GB",
      color: "Pink",
      condition: "EX_UK" as const,
      batteryHealth: 78,
      priceKES: 44999,
      priceUSD: 346,
      marketPriceKES: 56000,
      marketPriceUSD: 431,
      isFeatured: false,
      images: img(IMG.iphone.slice(2), 2),
      description: "Dual camera system, A15 chip. Minor scratches on camera lens area.",
    },
    {
      name: "iPhone 13 Mini 128GB Midnight",
      modelName: "iPhone 13 Mini",
      storageCapacity: "128GB",
      ram: "4GB",
      color: "Midnight",
      condition: "EX_UK" as const,
      batteryHealth: 76,
      priceKES: 38999,
      priceUSD: 300,
      marketPriceKES: 50000,
      marketPriceUSD: 385,
      isFeatured: false,
      images: img(IMG.iphone.slice(3), 2),
      description: "Compact 5.4 screen. Fits in any pocket. Dual camera. Screen in perfect condition.",
    },
    {
      name: "iPhone 12 Pro Max 256GB Pacific Blue",
      modelName: "iPhone 12 Pro Max",
      storageCapacity: "256GB",
      ram: "6GB",
      color: "Pacific Blue",
      condition: "REFURBISHED" as const,
      batteryHealth: 88,
      priceKES: 42999,
      priceUSD: 331,
      marketPriceKES: 54000,
      marketPriceUSD: 415,
      isFeatured: false,
      images: img(IMG.iphone.slice(4), 2),
      description: "Professionally refurbished. New battery, cleaned logic board. 5G enabled.",
    },
    {
      name: "iPhone 12 Pro 128GB Gold",
      modelName: "iPhone 12 Pro",
      storageCapacity: "128GB",
      ram: "6GB",
      color: "Gold",
      condition: "REFURBISHED" as const,
      batteryHealth: 86,
      priceKES: 36999,
      priceUSD: 285,
      marketPriceKES: 46000,
      marketPriceUSD: 354,
      isFeatured: false,
      images: img(IMG.iphone.slice(5), 2),
      description: "LiDAR scanner, A14 Bionic. Battery replaced professionally.",
    },
    {
      name: "iPhone 12 256GB Purple",
      modelName: "iPhone 12",
      storageCapacity: "256GB",
      ram: "4GB",
      color: "Purple",
      condition: "REFURBISHED" as const,
      batteryHealth: 84,
      priceKES: 31999,
      priceUSD: 246,
      marketPriceKES: 40000,
      marketPriceUSD: 308,
      isFeatured: false,
      images: img(IMG.iphone.slice(6), 2),
      description: "5G, OLED screen. Battery and screen cleaned. Minor frame wear.",
    },
    {
      name: "iPhone 12 Mini 64GB White",
      modelName: "iPhone 12 Mini",
      storageCapacity: "64GB",
      ram: "4GB",
      color: "White",
      condition: "REFURBISHED" as const,
      batteryHealth: 82,
      priceKES: 27999,
      priceUSD: 215,
      marketPriceKES: 34000,
      marketPriceUSD: 262,
      isFeatured: false,
      images: img(IMG.iphone.slice(7), 2),
      description: "Compact. OLED display, A14 chip. Body refurbished to Grade A condition.",
    },
    {
      name: "iPhone 11 Pro 256GB Midnight Green",
      modelName: "iPhone 11 Pro",
      storageCapacity: "256GB",
      ram: "4GB",
      color: "Midnight Green",
      condition: "USED" as const,
      batteryHealth: 74,
      priceKES: 28999,
      priceUSD: 223,
      marketPriceKES: 36000,
      marketPriceUSD: 277,
      isFeatured: false,
      images: img(IMG.iphone.slice(8), 2),
      description: "Triple camera system. Battery below recommended 80%. Screen has very minor micro-scratches under direct light. Works perfectly.",
    },
    {
      name: "iPhone 11 64GB Product Red",
      modelName: "iPhone 11",
      storageCapacity: "64GB",
      ram: "4GB",
      color: "Product Red",
      condition: "USED" as const,
      batteryHealth: 73,
      priceKES: 21999,
      priceUSD: 169,
      marketPriceKES: 28000,
      marketPriceUSD: 215,
      isFeatured: false,
      images: img(IMG.iphone.slice(9), 2),
      description: "Dual camera, Face ID. Battery needs monitoring. Slight scratch on frame side.",
    },
    {
      name: "iPhone SE 2022 128GB Starlight",
      modelName: "iPhone SE 2022",
      storageCapacity: "128GB",
      ram: "4GB",
      color: "Starlight",
      condition: "BRAND_NEW" as const,
      batteryHealth: null,
      priceKES: 35999,
      priceUSD: 277,
      marketPriceKES: 45000,
      marketPriceUSD: 346,
      isFeatured: true,
      images: img(IMG.iphone, 2),
      description: "Brand new, sealed in box. A15 Bionic, 5G, Touch ID. Best entry-level iPhone.",
    },
    {
      name: "iPhone 15 256GB Pink",
      modelName: "iPhone 15",
      storageCapacity: "256GB",
      ram: "6GB",
      color: "Pink",
      condition: "BRAND_NEW" as const,
      batteryHealth: null,
      priceKES: 72999,
      priceUSD: 562,
      marketPriceKES: 90000,
      marketPriceUSD: 692,
      isFeatured: true,
      images: img(IMG.iphone.slice(1), 2),
      description: "Brand new, sealed. USB-C, Dynamic Island, A16 Bionic. Pink colorway.",
    },
    {
      name: "iPhone 13 128GB Green",
      modelName: "iPhone 13",
      storageCapacity: "128GB",
      ram: "4GB",
      color: "Green",
      condition: "REFURBISHED" as const,
      batteryHealth: 83,
      priceKES: 41999,
      priceUSD: 323,
      marketPriceKES: 52000,
      marketPriceUSD: 400,
      isFeatured: false,
      images: img(IMG.iphone.slice(2), 2),
      description: "Screen replaced with OEM part. Body professionally cleaned. Great condition.",
    },
    {
      name: "iPhone X 256GB Space Gray",
      modelName: "iPhone X",
      storageCapacity: "256GB",
      ram: "3GB",
      color: "Space Gray",
      condition: "USED" as const,
      batteryHealth: 68,
      priceKES: 17999,
      priceUSD: 138,
      marketPriceKES: 24000,
      marketPriceUSD: 185,
      isFeatured: false,
      images: img(IMG.iphone.slice(3), 2),
      description: "OLED screen, Face ID. Battery significantly degraded — budget option. Screen in good condition.",
    },
    {
      name: "iPhone 14 Pro 256GB Gold",
      modelName: "iPhone 14 Pro",
      storageCapacity: "256GB",
      ram: "6GB",
      color: "Gold",
      condition: "EX_UK" as const,
      batteryHealth: 87,
      priceKES: 68999,
      priceUSD: 531,
      marketPriceKES: 86000,
      marketPriceUSD: 662,
      isFeatured: false,
      images: img(IMG.iphone.slice(4), 2),
      description: "Dynamic Island, Always-On Display. 48MP ProRAW camera. Gold finish, minimal wear.",
    },
  ];

  // ---- SAMSUNGS (15) ----
  const samsungs = [
    {
      name: "Samsung Galaxy S24 Ultra 256GB Titanium Black",
      modelName: "Galaxy S24 Ultra",
      storageCapacity: "256GB",
      ram: "12GB",
      color: "Titanium Black",
      condition: "EX_UK" as const,
      batteryHealth: 97,
      priceKES: 98999,
      priceUSD: 762,
      marketPriceKES: 125000,
      marketPriceUSD: 962,
      isFeatured: true,
      images: img(IMG.samsung, 3),
      description: "S Pen included. 200MP camera. Titanium frame. Near flawless condition.",
    },
    {
      name: "Samsung Galaxy S24 Ultra 512GB Titanium Gray",
      modelName: "Galaxy S24 Ultra",
      storageCapacity: "512GB",
      ram: "12GB",
      color: "Titanium Gray",
      condition: "BRAND_NEW" as const,
      batteryHealth: null,
      priceKES: 128999,
      priceUSD: 992,
      marketPriceKES: 158000,
      marketPriceUSD: 1215,
      isFeatured: true,
      images: img(IMG.samsung.slice(1), 2),
      description: "Brand new, sealed. AI-powered Galaxy features. Best Android flagship 2024.",
    },
    {
      name: "Samsung Galaxy S24 Plus 256GB Cobalt Violet",
      modelName: "Galaxy S24 Plus",
      storageCapacity: "256GB",
      ram: "12GB",
      color: "Cobalt Violet",
      condition: "EX_UK" as const,
      batteryHealth: 95,
      priceKES: 72999,
      priceUSD: 562,
      marketPriceKES: 92000,
      marketPriceUSD: 708,
      isFeatured: false,
      images: img(IMG.samsung.slice(2), 2),
      description: "Snapdragon 8 Gen 3. 4900mAh battery. Almost new condition.",
    },
    {
      name: "Samsung Galaxy S24 128GB Marble Gray",
      modelName: "Galaxy S24",
      storageCapacity: "128GB",
      ram: "8GB",
      color: "Marble Gray",
      condition: "EX_UK" as const,
      batteryHealth: 93,
      priceKES: 59999,
      priceUSD: 462,
      marketPriceKES: 76000,
      marketPriceUSD: 585,
      isFeatured: false,
      images: img(IMG.samsung.slice(3), 2),
      description: "Compact flagship. Galaxy AI features. Good condition, minor screen micro-scratches.",
    },
    {
      name: "Samsung Galaxy S23 Ultra 512GB Phantom Black",
      modelName: "Galaxy S23 Ultra",
      storageCapacity: "512GB",
      ram: "12GB",
      color: "Phantom Black",
      condition: "EX_UK" as const,
      batteryHealth: 88,
      priceKES: 79999,
      priceUSD: 615,
      marketPriceKES: 100000,
      marketPriceUSD: 769,
      isFeatured: false,
      images: img(IMG.samsung.slice(4), 2),
      description: "200MP camera, S Pen. Snapdragon 8 Gen 2. Good condition.",
    },
    {
      name: "Samsung Galaxy S23 Plus 256GB Lavender",
      modelName: "Galaxy S23 Plus",
      storageCapacity: "256GB",
      ram: "8GB",
      color: "Lavender",
      condition: "EX_UK" as const,
      batteryHealth: 85,
      priceKES: 59999,
      priceUSD: 462,
      marketPriceKES: 76000,
      marketPriceUSD: 585,
      isFeatured: false,
      images: img(IMG.samsung.slice(5), 2),
      description: "4700mAh battery, 45W charging. Snapdragon 8 Gen 2. Light frame wear.",
    },
    {
      name: "Samsung Galaxy S23 128GB Cream",
      modelName: "Galaxy S23",
      storageCapacity: "128GB",
      ram: "8GB",
      color: "Cream",
      condition: "EX_UK" as const,
      batteryHealth: 82,
      priceKES: 49999,
      priceUSD: 385,
      marketPriceKES: 64000,
      marketPriceUSD: 492,
      isFeatured: false,
      images: img(IMG.samsung.slice(6), 2),
      description: "Compact and premium. 50MP camera. Good everyday condition.",
    },
    {
      name: "Samsung Galaxy S22 Ultra 256GB Burgundy",
      modelName: "Galaxy S22 Ultra",
      storageCapacity: "256GB",
      ram: "12GB",
      color: "Burgundy",
      condition: "REFURBISHED" as const,
      batteryHealth: 86,
      priceKES: 54999,
      priceUSD: 423,
      marketPriceKES: 68000,
      marketPriceUSD: 523,
      isFeatured: false,
      images: img(IMG.samsung.slice(7), 2),
      description: "Built-in S Pen. Professionally refurbished. 108MP quad camera.",
    },
    {
      name: "Samsung Galaxy S22 Plus 128GB Graphite",
      modelName: "Galaxy S22 Plus",
      storageCapacity: "128GB",
      ram: "8GB",
      color: "Graphite",
      condition: "REFURBISHED" as const,
      batteryHealth: 84,
      priceKES: 42999,
      priceUSD: 331,
      marketPriceKES: 54000,
      marketPriceUSD: 415,
      isFeatured: false,
      images: img(IMG.samsung, 2),
      description: "4500mAh, 45W charging. Screen professionally replaced. Clean body.",
    },
    {
      name: "Samsung Galaxy S22 128GB Pink Gold",
      modelName: "Galaxy S22",
      storageCapacity: "128GB",
      ram: "8GB",
      color: "Pink Gold",
      condition: "REFURBISHED" as const,
      batteryHealth: 83,
      priceKES: 36999,
      priceUSD: 285,
      marketPriceKES: 46000,
      marketPriceUSD: 354,
      isFeatured: false,
      images: img(IMG.samsung.slice(1), 2),
      description: "Compact, elegant. Snapdragon 8 Gen 1. Refurbished to Grade A.",
    },
    {
      name: "Samsung Galaxy Z Fold 5 256GB Phantom Black",
      modelName: "Galaxy Z Fold 5",
      storageCapacity: "256GB",
      ram: "12GB",
      color: "Phantom Black",
      condition: "EX_UK" as const,
      batteryHealth: 91,
      priceKES: 135999,
      priceUSD: 1046,
      marketPriceKES: 170000,
      marketPriceUSD: 1308,
      isFeatured: true,
      images: img(IMG.samsung.slice(2), 2),
      description: "Foldable flagship. 7.6 inch AMOLED inner screen. S Pen compatible. Pristine condition.",
    },
    {
      name: "Samsung Galaxy Z Flip 5 256GB Mint",
      modelName: "Galaxy Z Flip 5",
      storageCapacity: "256GB",
      ram: "8GB",
      color: "Mint",
      condition: "EX_UK" as const,
      batteryHealth: 93,
      priceKES: 82999,
      priceUSD: 638,
      marketPriceKES: 105000,
      marketPriceUSD: 808,
      isFeatured: false,
      images: img(IMG.samsung.slice(3), 2),
      description: "Large cover screen. FlexHinge design. Very good condition.",
    },
    {
      name: "Samsung Galaxy S21 Ultra 256GB Phantom Silver",
      modelName: "Galaxy S21 Ultra",
      storageCapacity: "256GB",
      ram: "12GB",
      color: "Phantom Silver",
      condition: "USED" as const,
      batteryHealth: 74,
      priceKES: 38999,
      priceUSD: 300,
      marketPriceKES: 50000,
      marketPriceUSD: 385,
      isFeatured: false,
      images: img(IMG.samsung.slice(4), 2),
      description: "100x Space Zoom camera. 5000mAh. Battery degraded — functions well. Frame has scratches.",
    },
    {
      name: "Samsung Galaxy S21 FE 128GB Graphite",
      modelName: "Galaxy S21 FE",
      storageCapacity: "128GB",
      ram: "6GB",
      color: "Graphite",
      condition: "REFURBISHED" as const,
      batteryHealth: 81,
      priceKES: 28999,
      priceUSD: 223,
      marketPriceKES: 36000,
      marketPriceUSD: 277,
      isFeatured: false,
      images: img(IMG.samsung.slice(5), 2),
      description: "Fan Edition. Snapdragon 888. 64MP triple camera. Good condition.",
    },
    {
      name: "Samsung Galaxy A54 128GB Awesome Violet",
      modelName: "Galaxy A54",
      storageCapacity: "128GB",
      ram: "8GB",
      color: "Awesome Violet",
      condition: "BRAND_NEW" as const,
      batteryHealth: null,
      priceKES: 32999,
      priceUSD: 254,
      marketPriceKES: 42000,
      marketPriceUSD: 323,
      isFeatured: false,
      images: img(IMG.samsung.slice(6), 2),
      description: "Brand new, sealed. IP67 dust and water resistant. 5000mAh, 5G.",
    },
  ];

  // ---- PIXELS (10) ----
  const pixels = [
    {
      name: "Google Pixel 8 Pro 256GB Obsidian",
      modelName: "Pixel 8 Pro",
      storageCapacity: "256GB",
      ram: "12GB",
      color: "Obsidian",
      condition: "EX_UK" as const,
      batteryHealth: 96,
      priceKES: 79999,
      priceUSD: 615,
      marketPriceKES: 100000,
      marketPriceUSD: 769,
      isFeatured: true,
      images: img(IMG.pixel, 3),
      description: "Google Tensor G3 chip. Temperature sensor. 7 years of OS updates. Near new.",
    },
    {
      name: "Google Pixel 8 Pro 512GB Bay",
      modelName: "Pixel 8 Pro",
      storageCapacity: "512GB",
      ram: "12GB",
      color: "Bay",
      condition: "EX_UK" as const,
      batteryHealth: 98,
      priceKES: 92999,
      priceUSD: 715,
      marketPriceKES: 115000,
      marketPriceUSD: 885,
      isFeatured: false,
      images: img(IMG.pixel.slice(1), 2),
      description: "Max storage Pixel 8 Pro. Porcelain rear. 50MP + 48MP + 48MP cameras. Pristine.",
    },
    {
      name: "Google Pixel 8 Pro 256GB Porcelain",
      modelName: "Pixel 8 Pro",
      storageCapacity: "256GB",
      ram: "12GB",
      color: "Porcelain",
      condition: "BRAND_NEW" as const,
      batteryHealth: null,
      priceKES: 85999,
      priceUSD: 662,
      marketPriceKES: 108000,
      marketPriceUSD: 831,
      isFeatured: false,
      images: img(IMG.pixel.slice(2), 2),
      description: "Brand new, sealed. Best-in-class AI photo processing. 7 years updates.",
    },
    {
      name: "Google Pixel 8 128GB Hazel",
      modelName: "Pixel 8",
      storageCapacity: "128GB",
      ram: "8GB",
      color: "Hazel",
      condition: "EX_UK" as const,
      batteryHealth: 94,
      priceKES: 55999,
      priceUSD: 431,
      marketPriceKES: 70000,
      marketPriceUSD: 538,
      isFeatured: false,
      images: img(IMG.pixel.slice(3), 2),
      description: "Tensor G3. Magic Eraser, Call Screen. Compact and clean.",
    },
    {
      name: "Google Pixel 8 256GB Obsidian",
      modelName: "Pixel 8",
      storageCapacity: "256GB",
      ram: "8GB",
      color: "Obsidian",
      condition: "EX_UK" as const,
      batteryHealth: 91,
      priceKES: 61999,
      priceUSD: 477,
      marketPriceKES: 78000,
      marketPriceUSD: 600,
      isFeatured: false,
      images: img(IMG.pixel.slice(4), 2),
      description: "Larger storage Pixel 8. AI-powered features. Excellent condition.",
    },
    {
      name: "Google Pixel 7 Pro 256GB Snow",
      modelName: "Pixel 7 Pro",
      storageCapacity: "256GB",
      ram: "12GB",
      color: "Snow",
      condition: "EX_UK" as const,
      batteryHealth: 84,
      priceKES: 54999,
      priceUSD: 423,
      marketPriceKES: 68000,
      marketPriceUSD: 523,
      isFeatured: false,
      images: img(IMG.pixel, 2),
      description: "Tensor G2, 5x telephoto lens. Good working condition.",
    },
    {
      name: "Google Pixel 7 128GB Lemongrass",
      modelName: "Pixel 7",
      storageCapacity: "128GB",
      ram: "8GB",
      color: "Lemongrass",
      condition: "EX_UK" as const,
      batteryHealth: 81,
      priceKES: 42999,
      priceUSD: 331,
      marketPriceKES: 54000,
      marketPriceUSD: 415,
      isFeatured: false,
      images: img(IMG.pixel.slice(1), 2),
      description: "Tensor G2 chip, 50MP camera. Reliable Google updates. Good condition.",
    },
    {
      name: "Google Pixel 7a 128GB Carbon",
      modelName: "Pixel 7a",
      storageCapacity: "128GB",
      ram: "8GB",
      color: "Carbon",
      condition: "EX_UK" as const,
      batteryHealth: 86,
      priceKES: 38999,
      priceUSD: 300,
      marketPriceKES: 49000,
      marketPriceUSD: 377,
      isFeatured: false,
      images: img(IMG.pixel.slice(2), 2),
      description: "Wireless charging, 90Hz display. Best mid-range Pixel. Clean condition.",
    },
    {
      name: "Google Pixel 6 Pro 256GB Stormy Black",
      modelName: "Pixel 6 Pro",
      storageCapacity: "256GB",
      ram: "12GB",
      color: "Stormy Black",
      condition: "REFURBISHED" as const,
      batteryHealth: 79,
      priceKES: 36999,
      priceUSD: 285,
      marketPriceKES: 46000,
      marketPriceUSD: 354,
      isFeatured: false,
      images: img(IMG.pixel.slice(3), 2),
      description: "Original Tensor chip. 50MP wide + 48MP tele. Refurbished screen. Battery approaching threshold.",
    },
    {
      name: "Google Pixel 6 128GB Kinda Coral",
      modelName: "Pixel 6",
      storageCapacity: "128GB",
      ram: "8GB",
      color: "Kinda Coral",
      condition: "REFURBISHED" as const,
      batteryHealth: 76,
      priceKES: 28999,
      priceUSD: 223,
      marketPriceKES: 36000,
      marketPriceUSD: 277,
      isFeatured: false,
      images: img(IMG.pixel.slice(4), 2),
      description: "First-gen Tensor. Coral color. Refurbished — body shows minor wear. Great budget Pixel.",
    },
  ];

  // Insert all products
  let count = 0;

  for (const p of iphones) {
    const productSlug = slug(`${p.modelName} ${p.storageCapacity} ${p.color} ${p.condition}`);
    await prisma.product.upsert({
      where: { slug: productSlug },
      create: { ...p, slug: productSlug, brandId: apple.id },
      update: { priceKES: p.priceKES, images: p.images },
    });
    count++;
  }

  for (const p of samsungs) {
    const productSlug = slug(`${p.modelName} ${p.storageCapacity} ${p.color} ${p.condition}`);
    await prisma.product.upsert({
      where: { slug: productSlug },
      create: { ...p, slug: productSlug, brandId: samsung.id },
      update: { priceKES: p.priceKES, images: p.images },
    });
    count++;
  }

  for (const p of pixels) {
    const productSlug = slug(`${p.modelName} ${p.storageCapacity} ${p.color} ${p.condition}`);
    await prisma.product.upsert({
      where: { slug: productSlug },
      create: { ...p, slug: productSlug, brandId: google.id },
      update: { priceKES: p.priceKES, images: p.images },
    });
    count++;
  }

  console.log(`✅ Seeded ${count} products`);
  console.log("🔑 Admin login: admin@voltamobile.co.ke / volta@admin2024");
  console.log("🌱 Seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
